version: "3.2"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongodb_catalog_data:/data/db
    ports:
      - 27017:27017

volumes:
  mongodb_catalog_data:
    external: false
